name: action
on: 
  push:
    branches:
      - test
  pull_request:
    types:
      - opened
    branches:
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "building..."
