name: test-if-||
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: for if or
        if: github.actor == 'ashish' || github.actor == 'ashishaluwala'
        run: echo "trigger"
